title: "Dr. Alejandro E. Rodríguez-Sánchez"
author: "Alejandro E. Rodríguez-Sánchez"
description: "" #"Made with <b style=\"color: #f45;\">&lt;3</b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n\n"
date_format: "%d-%m-%Y"
mathjax: true

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false            # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "README.md"}
  - {title: Cursos, file: "cursos.md"}
  - {title: Publicaciones, file: "publicaciones.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
#   - {title: Mail, icon: envelope, url: "mailto:niklasbuschmann@users.noreply.github.com"}
#   - {title: Mi blog personal, url: "https://blogmateria.com"}
#   - {title: ORCiD, url: "https://orcid.org/0000-0003-3397-5261"}
#   - {title: Google Scholar, icon: scholar, url: "https://scholar.google.com.mx/citations?user=eo-JXcoAAAAJ&hl=es"}
#   - {title: Researchgate, url: "https://www.researchgate.net/profile/Alejandro-Rodriguez-Sanchez-4"}
#   - {title: Github, icon: github, url: "https://github.com/aerodriguezsanchez"}
  #- {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
disqus_shortname: ""    # see https://disqus.com/
isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
